spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: customer_group
    producer:
      bootstrap-servers: localhost:9092
    admin:
      properties:
        bootstrap:
          servers: localhost:9092
  datasource:
    url: jdbc:h2:~/TestDatabase



kafka-helper:
  max-retry-count: 2
  retry-group: retry-group
  retry-cron-job: 0 2 18 * * *
  dead-topic: customer-dead-topic
  retry-topic: customer-retry-topic
  enabled: false
